---
- name: Red Hat Subscription Release
  hosts: soe_{{ soe_version }}

  tasks:

    - name: Unsubscribe from Red Hat Satellite
      community.general.redhat_subscription:
        state: absent
      become: yes