---
- name: Software Patching
  hosts: soe_{{ soe_version }}
  gather_facts: yes

  vars_files:
    - group_vars/soe_vars.yml
    - group_vars/vault.yml

  tasks:

    - name: Clean up repos
      ansible.builtin.command: rm -rf /etc/yum.repos.d/*
      become: true
    
    - name: Install Katello-CA 
      ansible.builtin.command: yum localinstall -y --nogpgcheck "{{ soe.rhsm_satellite_url }}"/pub/katello-ca-consumer-latest.noarch.rpm
      become: yes

    - name: Subscribe to Satellite
      community.general.redhat_subscription:
        force_register: yes
        org_id: "{{ soe.org_id }}"
        activationkey: "{{ soe.activationkey }}"
      become: yes

    - name: Ensure RHSM managed repos
      block:
        - name: Retrieve RHSM config
          ansible.builtin.command: cat /etc/rhsm/rhsm.conf
          register: result_rhsmconf
          become: true
        - name: Manage generation of yum repos for subscribed content switch
          ansible.builtin.command: subscription-manager config --rhsm.manage_repos=1
          when: '"manage_repos = 1" in result_rhsmconf'
          become: true

    - name: Perform full patching
      ansible.builtin.dnf:
        name: "*"
        state: latest
      become: yes