---
- name: Package Installation and Services Configuration
  hosts: soe_{{ soe_version }}

  tasks:

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - realmd
          - sssd
          - samba-common
          - samba-common-tools
          - samba-winbind
          - samba-winbind-clients
          - krb5-workstation
          - openldap-clients
          - wget
          - vim
          - policycoreutils-python-utils
          - fapolicyd
        state: present
      become: yes

    - name: Start and enable sshd
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: yes
      become: yes

    - name: Enable fapolicyd
      ansible.builtin.systemd:
        name: fapolicyd.service
        enabled: yes
        state: started
      become: yes

    - name: Remove cockpit service
      ansible.builtin.dnf:
        name:
          - cockpit
          - nfs-utils
        state: absent