---
- name: Install developer software packages
  ansible.builtin.dnf:
    name:
      - snapd
      - golang
      - nodejs010
      - numpy
      - p7zip 
      - pzip-gui
      - python36
      - python36-pymssql
      - python36-scipy
      - python36-sqlalchemy
      - python36-urllib3
      - R
    become: true
...
# How to install p7zip on RHEL8: https://linuxconfig.org/how-to-install-p7zip-on-redhat-8